### PR TITLE
add one localized string and one property

### PR DESCRIPTION
**Pull request by yeahren**
1) add localized string "Last Updated:"; 
2) add new property "dateFormatter" for custom date formatter;

### CODE REVIEW

**Comment by typeoneerror** [comment]
Not sure you want to retain a delegate. Potentially creating some leaky code.

**Comment by yeahren** [comment]
i will be release the delegate in header view dealloc function, is it not so good?

**Comment by typeoneerror** [comment]
This answer has a good explanation (I think):

http://stackoverflow.com/questions/4795871/delegates-retain-or-assign-release

**Comment by yeahren** [comment]
thank you, dude

**Pull request closed without merging**
